import { ArrowUpRight, Check, ChevronRight, CircleAlert, Lightbulb, TrendingDown, TrendingUp } from "lucide-react";
import { Link } from "react-router-dom";
import { cn } from "@/lib/utils";

export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-violet-300">{eyebrow || "Energy intelligence"}</p><h1 className="font-display text-3xl font-semibold tracking-tight sm:text-4xl">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p>}</div>{action}</div>; }

export function SectionHeading({ title, description, action }: { title: string; description?: string; action?: React.ReactNode }) { return <div className="mb-4 flex items-end justify-between gap-3"><div><h2 className="font-display text-lg font-semibold tracking-tight">{title}</h2>{description && <p className="mt-1 text-xs text-muted-foreground">{description}</p>}</div>{action}</div>; }

export function Trend({ value, positiveIsGood = false }: { value: number; positiveIsGood?: boolean }) { const up = value >= 0; const good = positiveIsGood ? up : !up; return <span className={cn("inline-flex items-center gap-1 text-xs font-semibold", good ? "text-emerald-400" : "text-amber-300")}>{up ? <TrendingUp className="size-3" /> : <TrendingDown className="size-3" />}{Math.abs(value).toFixed(1)}%</span>; }

export function TinySparkline({ values, color = "#8b7cf6" }: { values: number[]; color?: string }) { const min = Math.min(...values); const max = Math.max(...values); const points = values.map((value, index) => `${(index / (values.length - 1)) * 100},${28 - ((value - min) / Math.max(max - min, 1)) * 22}`).join(" "); return <svg viewBox="0 0 100 30" preserveAspectRatio="none" className="h-8 w-24 overflow-visible"><polyline fill="none" stroke={color} strokeWidth="2.25" strokeLinecap="round" strokeLinejoin="round" points={points} /></svg>; }

export function ArrowLink({ to, children }: { to: string; children: React.ReactNode }) { return <Link to={to} className="group inline-flex items-center gap-1.5 text-xs font-semibold text-blue-300 transition-colors hover:text-blue-200">{children}<ArrowUpRight className="size-3.5 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></Link>; }

export function EmptyState() { return <div className="flex min-h-[360px] flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-card/60 p-8 text-center"><div className="mb-5 grid size-16 place-items-center rounded-2xl bg-violet-500/10 text-violet-300"><Lightbulb className="size-7" /></div><h3 className="font-display text-xl font-semibold">Your energy journey starts here.</h3><p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground">We need a little more consumption history before we can personalize your insights.</p><button className="mt-6 rounded-xl bg-violet-500 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-violet-500/20 transition hover:bg-violet-400">Add Consumption Data</button></div>; }

export function StatusPill({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "neutral" | "success" | "warning" | "danger" }) { return <span className={cn("inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold", tone === "success" && "bg-emerald-400/10 text-emerald-300", tone === "warning" && "bg-amber-400/10 text-amber-300", tone === "danger" && "bg-rose-400/10 text-rose-300", tone === "neutral" && "bg-blue-400/10 text-blue-300")}>{tone === "success" && <Check className="size-3" />}{tone === "warning" && <CircleAlert className="size-3" />}{children}</span>; }
