import { useEffect, useState } from "react";
import { Activity, ArrowUpRight, BarChart3, Clock3, Lightbulb, ShieldAlert, Sparkles, Target } from "lucide-react";
import { insightService } from "@/services/api";
import type { Insight, InsightType } from "@/types";
import { PageHeader, StatusPill } from "@/components/common";
import { SkeletonList } from "@/components/ui/app-skeletons";

const tabs = [{ label: "All", value: "ALL" }, { label: "Benchmark", value: "BENCHMARK" }, { label: "Saving", value: "SAVING" }, { label: "Peak usage", value: "PEAK_USAGE" }, { label: "Anomaly", value: "ANOMALY" }, { label: "Recommendation", value: "RECOMMENDATION" }, { label: "Forecast", value: "FORECAST" }];
const iconFor: Record<InsightType, { icon: React.ElementType; tone: string; label: string }> = { BENCHMARK: { icon: BarChart3, tone: "blue", label: "Benchmark" }, SAVING: { icon: Target, tone: "green", label: "Saving" }, PEAK_USAGE: { icon: Clock3, tone: "violet", label: "Peak usage" }, ANOMALY: { icon: ShieldAlert, tone: "amber", label: "Anomaly" }, RECOMMENDATION: { icon: Lightbulb, tone: "yellow", label: "Recommendation" }, FORECAST: { icon: Activity, tone: "cyan", label: "Forecast" } };
export default function InsightsPage() { const [insights, setInsights] = useState<Insight[] | null>(null); const [active, setActive] = useState("ALL"); useEffect(() => { insightService.getByHousehold(1).then(setInsights); }, []); const filtered = insights?.filter((item) => active === "ALL" || item.type === active) || []; return <div className="animate-in fade-in duration-500"><PageHeader eyebrow="Personalized intelligence" title="Energy insights" description="Signals from your usage, translated into practical next steps." action={<div className="rounded-xl border border-border bg-card px-3 py-2 text-xs text-muted-foreground"><span className="mr-2 inline-block size-1.5 rounded-full bg-violet-300" />{insights?.length || 5} insights this month</div>} /><div className="mb-6 flex gap-2 overflow-x-auto pb-1">{tabs.map((tab) => <button key={tab.value} onClick={() => setActive(tab.value)} className={`shrink-0 rounded-xl px-3 py-2 text-xs font-semibold transition ${active === tab.value ? "bg-violet-500 text-white shadow-lg shadow-violet-500/15" : "border border-border bg-card text-muted-foreground hover:text-foreground"}`}>{tab.label}</button>)}</div>{!insights ? <SkeletonList /> : <div className="grid gap-4 lg:grid-cols-2">{filtered.map((item) => { const meta = iconFor[item.type]; const Icon = meta.icon; return <article key={item.id} className="group rounded-2xl border border-border/70 bg-card p-5 transition-all hover:-translate-y-0.5 hover:border-violet-400/30 sm:p-6"><div className="flex items-start gap-4"><div className={`grid size-11 shrink-0 place-items-center rounded-xl ${meta.tone === "amber" ? "bg-amber-400/10 text-amber-300" : meta.tone === "green" ? "bg-emerald-400/10 text-emerald-300" : meta.tone === "blue" ? "bg-blue-400/10 text-blue-300" : "bg-violet-400/10 text-violet-300"}`}><Icon className="size-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><StatusPill tone={meta.tone === "amber" ? "warning" : "neutral"}>{meta.label}</StatusPill><span className="text-[11px] text-muted-foreground">{new Date(item.createdAt).toLocaleDateString("en-IN", { day: "numeric", month: "short" })}</span></div><p className="mt-4 text-sm font-medium leading-6">{item.message}</p><button className="mt-5 inline-flex items-center gap-1.5 text-xs font-semibold text-blue-300 opacity-90 transition group-hover:opacity-100">Take a closer look <ArrowUpRight className="size-3.5" /></button></div></div></article>; })}</div>}</div>; }
